[default]
enabled_files = ["*.jtl"]
exclude_files = []
metrics = ["responseTime", "latency", "errorCount"]
percentiles = [50, 90, 95, 99]

[default.output_settings]
base_dir = "analysis_output"
plots_dir = "plots"
logs_dir = "logs"
reports_dir = "reports"

[default.log_settings]
rotation = "10 MB"
retention = "1 month"
compression = "zip"
level = "INFO"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

[development]
log_settings.level = "DEBUG"

[production]
log_settings.level = "WARNING" 